### ISSUE TITLE
args.folders

### ISSUE THREAD

**Issue by 13121283123** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#26] opened 2021-06-05 07:15 UTC
I am very interested in your article. I would like to ask what is the default value of args.folders in combine_urc.py in your code. Thank you for your reply

 classifiers = [
        load_classifier(
            os.path.join(args.model_path, folder), args.dataset, args.cuda,
            args.gpu
        ) for folder in args.folders
    ]

**Comment by White-Link** [comment] 2021-06-05 18:33
Hi, thank you for your interest in our work!

Suppose that you trained the model with different sets of hyperparameters on the same dataset and that you saved one in a folder `'A'` and the other one in folder `'B'`, both being located in the directory given to the `model_path` option. Then `args.folders` should be the list `['A', 'B']` to combine both models; the corresponding command-line option should be used as `--folders A B`.

Feel free to reopen the issue if you have any other question!

**Comment by 13121283123** [comment] 2021-06-06 07:26
Thank you very very much, but I'm very sorry to bother you again, this error 'non-empty 4D input tensor expected but got: [50, 1, 1, 0]' when I run combine_ucr.py. I analyze the reason and report the error when executing this line of code.
Train_representations = numpy.concatenate ([.
&nbsp; &nbsp; &nbsp; C.encode (train) for c in classifiers.
&nbsp; &nbsp;], axis=1).
What I want to ask you is：
train, train_labels, test, test_labels = ucr.load_UCR_dataset (.
Args.path, args.dataset.
).
where the train here is [].
If you execute c.encode (train) again, you will get the following error.
Non-empty 4D input tensor expected but got: [50, 1, 1, 0]
I don't understand why you input a null train into the network.&nbsp;
The dataset I use in the code is Cricket_X，








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "White-Link/UnsupervisedScalableRepresentationLearningTimeSeries"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月6日(星期天) 凌晨2:33
***@***.***&gt;;
抄送:&nbsp;"Changxia ***@***.******@***.***&gt;;
主题:&nbsp;Re: [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries] args.folders (#26)





 
Closed #26.

**Comment by White-Link** [comment] 2021-06-09 12:30
Hi, sorry about the late answer.

When I run this script on my side with the recommended dependencies, everything works as intended; did you make sure to use the package versions listed in the `README.md` file ?

Otherwise, In light of the error that you obtain, the problem might be related to the data that you are using. Did you download them from the [official webpage](https://www.cs.ucr.edu/%7Eeamonn/time_series_data_2018/)?

**Comment by White-Link** [comment] 2021-06-22 09:19
I am closing the issue for now, since the code seems working as intended. Feel free to re-open it if you still encounter the issue!

**Closed as completed by White-Link** 2021-06-22 09:19 UTC
